### ISSUE TITLE
Add micro benchmarks for comparison functions in C++ SDK

### ISSUE THREAD

**Issue by cthulhu-irl** [trytouca/trytouca#108]
Touca's cpp-sdk is subject to performance and layout improvements (for example as #107 suggests) and features like supporting blobs as data_point are in discussion.

As performance of changes aren't measured yet, these changes and their impact aren't quite comparable, thus there is a need of adding benchmarking.

**Comment by ghorbanzade** [comment]
This issue is no longer relevant. We've removed the standalone Touca Comparator service which was in C++. Touca v1.8  now has a built-in comparison service written in TypeScript. We've also added micro-benchmarks to the implementations to keep an eye on the performance of the new service. Since C++ comparison logic is no longer used in the server, we recently moved it out of the core library and into the C++ CLI executable. We plan to remove that CLI executable in an upcoming release.
