### ISSUE TITLE
Move client to an event-based update model

### ISSUE THREAD

**Issue by Rossh87** [trytouca/trytouca#376]
(moving to Github from [this discussion](https://discord.com/channels/807669589294317598/807676435203883052/1029207061017415740))

# Description
Angular app client currently polls API server for data updates.  Pages re-request all their data every 10 seconds.  This change would move the client to a server event based model, minimizing redundant network traffic and improving the client's response time to server-side changes.

# Suggested approach
Send events to authenticated clients whenever Redis cache elements are invalidated/removed, and let the client decide whether or not to refetch the impacted data.  I favor this approach for two reasons:
1. It's simpler to implement/extend than trying to proactively send updated data in the event itself.  It's easier to reason about potential race conditions, and doesn't require any fussy data merging on the client side.
2. It avoids broadcasting useless data to clients that don't need it.
3. Would play nicely with client-side caching if you ever wanted to add it.

# Drawbacks
1. Will cause a spike of HTTP requests whenever a cache invalidation occurs.  I think this can be mitigated by adding a bit of delay before the server event is sent to too many clients; that should ensure the cache is repopulated before the bulk of the requests come through.
2. In some cases this approach will cause more network and database usage than including data in the server event would.  For example, if two clients are viewing the `batch list` page, and one of them submits a new batch, it is more expensive to refetch all the relevant batches again than it would be to append the new batch to the list that the clients already have in memory.  I think points 1 and 2 above outweigh this concern, but others might reasonably disagree.  At worst, taking the cache invalidation approach outlined above doesn't preclude using a data broadcasting strategy for cases where a complete refetch would be too expensive.

# Questions
1. Do you think there will ever be value in having the two-way communication that websockets offer?  If not, I would favor using server events, since they're simple enough to implement without adding any third-party dependencies.
2. Do you/would you like to support scenarios where multiple instances of the Touca API server run as part of the same service, e.g. behind a load balancer?  If so, `push` events will need to go through the async queue.

Sorry for writing a novel.  I'm always happy to have my mind changed, and I really welcome any suggestions or criticisms before getting started!

**Comment by ghorbanzade** [comment]
Hi @Rossh87,

This is a wonderful proposal. Thank you for putting good thoughts into writing the description, outlining potential drawbacks.

Currently, the client does not re-fetch **all** the data every 10 seconds. Only the 4 main pages that use a list, re-fetch that list using polling. We've added ugly logic to the front-end code to avoid re-fetching some data. See an example [here](https://github.com/trytouca/trytouca/blob/main/app/src/app/home/pages/suite/suite.service.ts#L172-L190). But this polling mechanism has to go and the sooner we can switch to Server-Side Events the better. This issue has very high business value so thanks so much for taking on it.

I don't think we need WebSockets at the moment. The use-cases I can think of are far out into the future. I'm also not sure how using a Redis cache to trigger SSE would work. So far, we only use Redis as job queue and for caching the API response. We could certainly opt to caching every response but we could decide this once we have a proof of concept, no? My suggestion is for us to break down the implementation work (we don't need to create separate issues) to the following:

1. Let's create a proof of concept for SSE communication. Perhaps, we can modify the backend's response for [batch page](https://github.com/trytouca/trytouca/blob/main/app/src/app/home/pages/batch/page.component.ts) to include a list of testcases that grows by one every second. So that when we click on the "Students" suite and then on any one of the 5 versions, we'd see a list of testcases that grows by one item every second.
2. Once the first PoC is done, we can figure out whether to use Redis or some other mechanism for updating the list.

Thoughts? CC'ing @committomaster to hear his thoughts.

**Comment by Rossh87** [comment]
I didn't know about Mongo change streams, very cool!  I was imagining a lot of complexity around retrieving the right patch data and emitting it at the right time; change streams address both of those concerns, so I'm happy with that approach.  Really good call, thanks!

Looking at the [code sample](https://github.com/trytouca/trytouca/blob/main/app/src/app/home/pages/suite/suite.service.ts#L172-L190) @ghorbanzade linked above, it might be wise to do some Angular refactoring before we jump into a full implementation of the server event stuff.  Specifically, I would consider moving fetching logic into entity-specific services (e.g. `BatchService`, `UserService`), rather than page-specific services.  That would make data-patching in response to server events *much* easier to reason about, and just be a lot more readable/extensible in general, IMO.

I would be happy to open a different issue for the Angular refactoring if that's something you'd like to consider;  in the meantime I can get started on a POC for server events.  Questions/concerns/feedback always welcome.  Thanks!

**Comment by ghorbanzade** [comment]
> It might be wise to do some Angular refactoring before we jump into a full implementation of the server event stuff.

@Rossh87, I see your point but I'm going to side with Mohajer on this and suggest that we pursue this cleanup after changes to the backend, assuming that wouldn't cause too much inconvenience. In general, we prefer to get to a working prototype fast, then iterate several times if needed to get things right.

> One issue if we opt to use change streams is that we'd require a Mongo replica set in dev and prod. Is that an infra change we can consider, @ghorbanzade?

@committomaster, yes we can certainly make any changes necessary to support any solution you'd come up with.

**Comment by Rossh87** [comment]
Sure thing!

I've started a [feature branch](https://github.com/Rossh87/trytouca/tree/server-events) in my fork for this feature.  Feel free to have a look/comment/whatever.  If it's easier, I can submit a PR against a new feature branch in your repo too--whatever you prefer!
