### ISSUE TITLE
Install script creates some local files as root

### ISSUE THREAD

**Issue by ghorbanzade** [trytouca/trytouca#76]
## Description

When running `install.sh`, Ehsan Ahangari found that files in directories like `/.touca/server/data/mongo` and `/.touca/server/data/minio` are installed as owned by root instead of the current user.

## Environment

Checked on Rocky Linux and Ubuntu

**Comment by Rossh87** [comment]
Any container that gets started without an explicit user id defaults to id `0`, which is root.  Since the redis/mongo/minio containers started by `docker-compose up` are running as root, any files they create in their respective volumes (which are mapped to `~/.touca/server/data` on the host file system by `docker-compose.prod.yaml`) will belong to root as well.  At least on my Ubuntu machine, they end up with `644` file permissions, so still readable by any other users/processes that might need them.  If you would like your containers to run with the `uid` of whoever runs the install script, you can [see this diff](https://github.com/trytouca/trytouca/compare/main...Rossh87:trytouca:docker-compose-user) for one approach that accomplishes that.

If anyone would like to test-drive the install process with this change active, you can run
```bash
bash <(curl -s https://gist.githubusercontent.com/Rossh87/e7107f1a5b1b52b94ad595b1cf1c5be3/raw/6e5bb335fbedf5cf9e6bec3640a3e9dac5f39407/touca-install.sh)
```
to see how it goes.  Probably worth trying on some different OSs/architectures.

Happy to submit this as a 'real' PR, but didn't want to spam if this isn't something you're ready for/isn't on the roadmap.

**Comment by ghorbanzade** [comment]
Hey @Rossh87,

Thanks so much for taking on this! Yup, this is exactly what we need and had previously discussed with @ehsan-touca. Can you think of any reason why running service containers as the current user would be a bad idea? If not, please go ahead and submit the PR. Your changes to the two files look good to me.

**Comment by Rossh87** [comment]
The two likeliest places for an issue to come up, IMO would be:
1. On a non-debian OS
2. In a CI/CD pipeline

Re: 1, I'm not super knowledgeable about the intricacies of cross-platform Docker, but I would think that if `bash` is available on the system the chance of problems is small, and if it's not available nothing else is going to work either.  Still, ideally someone with a Mac would run the install script I linked above and make sure everything works as expected before merging.

Re: 2, it looks like production deployments are handled by Kubernetes/Helm, not Docker, so no impacts there.  If there are no Github Actions/Cloud Build/whatever running integration tests out in the ether, then that's not a concern.  If there are... the easiest way to find out is pry just to trigger a run on a branch that has the changes and see what happens.  Exciting! But I think the likelihood of issues is low.

I'll update the `dev` and `test` `docker-compose` files to match `prod` and get you a PR soon.  Thanks for the input!

**Comment by ghorbanzade** [comment]
Thank you for the great perspective. Spot on. I tested this on my machine (Mac M1) and confirmed no issues. I don't think we should be worried about 1. If users don't have bash, they wouldn't be able to use the install script either. For 2, we have a `self-hosted-install` GitHub Actions that runs manually or every 6 hours. But not all prod instances of Touca use Kubernetes. In fact, we don't think anyone is using our Helm Chart at the moment. So one potential concern is what happens to teams who are using this `docker-compose.prod.yml` and for whom `/data` has root permissions. I think they'd need to `sudo chown` manually...

**Comment by ghorbanzade** [comment]
While it is possible to modify the install script to automatically check for permissions and sudo chown them if necessary, I don't think that would be needed: We can manually reach all teams and ask them to change permissions. Looking forward to the PR. :)
